### Levenshtein Distance 

In [21]:
def edit_dist(string1, string2):
    n = len(string1)
    m = len(string2)
    mat = np.zeros((n+1,m+1))
    mat[:,0] = np.arange(n+1)
    mat[0,:] = np.arange(m+1)
    for i in range(1, n+1):
        for j in range(1, m+1):
            arg1 = mat[i-1,j]+1
            arg2 = mat[i,j-1]+1
            arg3 = mat[i-1, j-1]
            if string1[i-1]!=string2[j-1]:
                arg3+=2
            mat[i,j] = min(arg1, arg2, arg3)
    print mat[::-1]
    return mat[n,m] 

In [22]:
string1 = "intention"
string2 = "execution"
edit_dist(string1, string2)

[[  9.   8.   9.  10.  11.  12.  11.  10.   9.   8.]
 [  8.   7.   8.   9.  10.  11.  10.   9.   8.   9.]
 [  7.   6.   7.   8.   9.  10.   9.   8.   9.  10.]
 [  6.   5.   6.   7.   8.   9.   8.   9.  10.  11.]
 [  5.   4.   5.   6.   7.   8.   9.  10.  11.  10.]
 [  4.   3.   4.   5.   6.   7.   8.   9.  10.   9.]
 [  3.   4.   5.   6.   7.   8.   7.   8.   9.   8.]
 [  2.   3.   4.   5.   6.   7.   8.   7.   8.   7.]
 [  1.   2.   3.   4.   5.   6.   7.   6.   7.   8.]
 [  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.]]


8.0